### ISSUE TITLE
Error when trying to load credentials on GitHub Actions

### ISSUE THREAD

**Issue by i10416** [abdolence/gcloud-sdk-rs#26]
I got the following error when I tried to access GCP component from GitHub Actions( Some tests need to access GCP components).

```sh
SystemError(FirestoreSystemError { public: FirestoreErrorPublicGenericDetails { code: "CredentialsJson(Error(\"data did not match any variant of untagged enum Credentials\", line: 0, column: 0))" }, message: "GCloud system error: credentials json error: data did not match any variant of untagged enum Credentials" })
```

Note that when I manually generate credentials file from GCP console and put it at `~/.config/gcloud/application_default_credentials.json`, it works.

Context: I generates credentials file by 'google-github-actions/auth@v0'.

```yaml
      - name: Authenticate to Google Cloud
        id: 'google-cloud-auth'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_ID_PROVIDER_ID }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
          create_credentials_file: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

```

possibly related issue

https://github.com/awslabs/aws-lambda-rust-runtime/issues/365
